name: Build projects

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: abel0b/setup-premake@v2.3
      with:
        version: "5.0.0-beta2"

    - name: Set up premake
      run: |
        premake5 --file=premake5.lua vs2022

    - name: Build Shard
      run: make -C Shard

    - name: Build Game
      run: make -C Game
