name: Build projects

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup premake5
      uses: abel0b/setup-premake@v2.3
      with:
        version: "5.0.0-beta2"

    - name: Use premake
      run: |
        premake5 --file=premake5.lua vs2022

    - name: Build Shard
      run: msbuild Shard.sln

    - name: Build Game
      run: msbuild Game.sln
